<?php

namespace GNKWLDF\LdfcorpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function findByLastOnline($max)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.online = :o')
            ->orderBy('p.lastOnline', 'DESC')
            ->setParameter('o' , true)
            ->setMaxResults($max)
            ->getQuery()
            ->getResult()
        ;
    }

    public function findOneByLastOnline()
    {
        $pages = $this->findByLastOnline(1);
        if(count($pages) > 0)
        {
            return $pages[0];
        }
        return null;
    }
}
