<?php

namespace GNKWLDF\LdfcorpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollRepository extends EntityRepository
{
    public function findLastActive()
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.active = :a')
            ->orderBy('p.updateDate', 'DESC')
            ->setParameter('a' , true)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
