<?php

namespace GNKWLDF\LdfcorpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLinkRepository extends EntityRepository
{
}
